package de.tud.fgdh.digiphenoms.fhir;

import org.hl7.fhir.r4.model.*;
import org.hl7.fhir.r4.model.Bundle.BundleEntryComponent;
import org.hl7.fhir.r4.model.Bundle.BundleType;

import java.util.Date;
import java.util.List;

/**
 * Shared test fixtures that mirror the resources generated by the Python
 * pipeline from the training CSV files in {@code pipeline/tests/fixtures/}.
 *
 * <p>The pipeline produces 38 resources from 3 patients: 3 Patient, 6 Condition,
 * 3 Encounter, 2 Device, 19 Observation, 2 DiagnosticReport, 3 QuestionnaireResponse.
 * This class provides builders for each resource type.</p>
 */
public final class TestFixtures {

    /* ----- OID systems (must match pipeline.yaml) ----- */
    public static final String PATIENT_OID =
            "urn:oid:2.16.840.1.113883.3.digiphenoms.patient";
    public static final String ASSESSMENT_OID =
            "urn:oid:2.16.840.1.113883.3.digiphenoms.assessment";
    public static final String MODULE_OID =
            "urn:oid:2.16.840.1.113883.3.digiphenoms.module";

    private TestFixtures() {}

    // -----------------------------------------------------------------------
    // Patients (3)  — matching patient-profile-overview_training.csv
    // -----------------------------------------------------------------------

    public static Patient patient(String alias, String gender, String birthDate) {
        Patient p = new Patient();
        p.setId("pat-" + alias);
        p.addIdentifier(new Identifier().setSystem(PATIENT_OID).setValue(alias));
        p.setGender(Enumerations.AdministrativeGender.fromCode(gender));
        p.setBirthDateElement(new DateType(birthDate));
        return p;
    }

    public static Patient patientAbc() {
        return patient("abc-1001", "female", "1985-06-01");
    }

    public static Patient patientDef() {
        return patient("def-1002", "male", "1978-11-20");
    }

    public static Patient patientGhi() {
        return patient("ghi-1003", "female", "1992-03-15");
    }

    // -----------------------------------------------------------------------
    // Conditions (6) — MS diagnosis + comorbidities
    // -----------------------------------------------------------------------

    public static Condition msCondition(String alias, String onsetDate) {
        Condition c = new Condition();
        c.setId("cond-ms-" + alias);
        c.addIdentifier(new Identifier().setSystem(PATIENT_OID)
                .setValue(alias + "-ms"));
        c.setSubject(new Reference("Patient/pat-" + alias));
        c.setCode(new CodeableConcept(new Coding()
                .setSystem("http://snomed.info/sct")
                .setCode("24700007")
                .setDisplay("Multiple sclerosis")));
        c.setOnset(new DateTimeType(onsetDate));
        c.setClinicalStatus(new CodeableConcept(new Coding()
                .setSystem("http://terminology.hl7.org/CodeSystem/condition-clinical")
                .setCode("active")));
        c.setVerificationStatus(new CodeableConcept(new Coding()
                .setSystem("http://terminology.hl7.org/CodeSystem/condition-ver-status")
                .setCode("confirmed")));
        return c;
    }

    public static Condition comorbidCondition(String alias, String type,
                                               String snomedCode, String display) {
        Condition c = new Condition();
        c.setId("cond-comorbid-" + alias + "-" + type);
        c.addIdentifier(new Identifier().setSystem(PATIENT_OID)
                .setValue(alias + "-comorbid-" + type));
        c.setSubject(new Reference("Patient/pat-" + alias));
        c.setCode(new CodeableConcept(new Coding()
                .setSystem("http://snomed.info/sct")
                .setCode(snomedCode)
                .setDisplay(display)));
        return c;
    }

    // -----------------------------------------------------------------------
    // Encounters (3) — matching wrapper-overview_training.csv
    // -----------------------------------------------------------------------

    public static Encounter encounter(String assessmentId, String patientAlias) {
        Encounter e = new Encounter();
        e.setId("enc-" + assessmentId);
        e.addIdentifier(new Identifier().setSystem(ASSESSMENT_OID).setValue(assessmentId));
        e.setStatus(Encounter.EncounterStatus.FINISHED);
        e.setClass_(new Coding()
                .setSystem("http://terminology.hl7.org/CodeSystem/v3-ActCode")
                .setCode("AMB"));
        e.setSubject(new Reference("Patient/pat-" + patientAlias));
        return e;
    }

    // -----------------------------------------------------------------------
    // Devices (2) — deduplicated by vendor identifier
    // -----------------------------------------------------------------------

    public static Device device(String vendorId, String name) {
        Device d = new Device();
        d.setId("dev-" + vendorId);
        d.addIdentifier(new Identifier().setSystem(MODULE_OID).setValue(vendorId));
        d.addDeviceName(new Device.DeviceDeviceNameComponent()
                .setName(name)
                .setType(Device.DeviceNameType.MANUFACTURERNAME));
        return d;
    }

    // -----------------------------------------------------------------------
    // Observations (samples for LCLA, 9HPT, SDMT, T25FW, MRI)
    // -----------------------------------------------------------------------

    public static Observation observation(String id, String patientAlias,
                                           String encounterId, String loincCode,
                                           String display) {
        Observation obs = new Observation();
        obs.setId(id);
        obs.addIdentifier(new Identifier().setSystem(MODULE_OID).setValue(id));
        obs.setStatus(Observation.ObservationStatus.FINAL);
        obs.setCode(new CodeableConcept(new Coding()
                .setSystem("http://loinc.org")
                .setCode(loincCode)
                .setDisplay(display)));
        obs.setSubject(new Reference("Patient/pat-" + patientAlias));
        if (encounterId != null) {
            obs.setEncounter(new Reference("Encounter/enc-" + encounterId));
        }
        obs.setEffective(new DateTimeType(new Date()));
        return obs;
    }

    public static Observation lclaObservation(String assessmentId, String moduleId,
                                               String patientAlias) {
        return observation(
                "obs-lcla-" + assessmentId + "-" + moduleId,
                patientAlias, assessmentId,
                "79880-1", "Low-Contrast Letter Acuity");
    }

    // -----------------------------------------------------------------------
    // DiagnosticReport (2) — MRI
    // -----------------------------------------------------------------------

    public static DiagnosticReport diagnosticReport(String id, String patientAlias) {
        DiagnosticReport dr = new DiagnosticReport();
        dr.setId(id);
        dr.addIdentifier(new Identifier().setSystem(PATIENT_OID).setValue(id));
        dr.setStatus(DiagnosticReport.DiagnosticReportStatus.FINAL);
        dr.setCode(new CodeableConcept(new Coding()
                .setSystem("http://loinc.org")
                .setCode("30799-1")
                .setDisplay("MRI Brain")));
        dr.setSubject(new Reference("Patient/pat-" + patientAlias));
        dr.setEffective(new DateTimeType(new Date()));
        return dr;
    }

    // -----------------------------------------------------------------------
    // QuestionnaireResponse (3) — Neuro-QoL, Anamnese
    // -----------------------------------------------------------------------

    public static QuestionnaireResponse questionnaireResponse(String id,
                                                               String patientAlias,
                                                               String encounterId) {
        QuestionnaireResponse qr = new QuestionnaireResponse();
        qr.setId(id);
        qr.setIdentifier(new Identifier().setSystem(MODULE_OID).setValue(id));
        qr.setStatus(QuestionnaireResponse.QuestionnaireResponseStatus.COMPLETED);
        qr.setSubject(new Reference("Patient/pat-" + patientAlias));
        if (encounterId != null) {
            qr.setEncounter(new Reference("Encounter/enc-" + encounterId));
        }
        return qr;
    }

    // -----------------------------------------------------------------------
    // Bundle builders
    // -----------------------------------------------------------------------

    /**
     * Build a realistic collection bundle matching the pipeline output
     * from the training fixtures: 3 patients, 3 encounters, 6 conditions,
     * 2 devices, 5 observations, 2 diagnostic reports, 2 QRs = 23 resources.
     */
    public static Bundle realisticCollectionBundle() {
        Bundle bundle = new Bundle();
        bundle.setType(BundleType.COLLECTION);

        // Tier 1: Patient + Condition
        addEntry(bundle, patientAbc());
        addEntry(bundle, patientDef());
        addEntry(bundle, patientGhi());
        addEntry(bundle, msCondition("abc-1001", "2018-03-15"));
        addEntry(bundle, msCondition("def-1002", "2015-07-22"));
        addEntry(bundle, msCondition("ghi-1003", "2020-11-03"));
        addEntry(bundle, comorbidCondition("abc-1001", "depression",
                "35489007", "Depressive disorder"));
        addEntry(bundle, comorbidCondition("abc-1001", "hypertension",
                "38341003", "Hypertensive disorder"));
        addEntry(bundle, comorbidCondition("def-1002", "diabetes",
                "73211009", "Diabetes mellitus"));

        // Tier 2: Encounter + Device
        addEntry(bundle, encounter("assess-2001", "abc-1001"));
        addEntry(bundle, encounter("assess-2002", "def-1002"));
        addEntry(bundle, encounter("assess-2003", "abc-1001"));
        addEntry(bundle, device("vendor-ipad-01", "iPad Pro MSPT"));
        addEntry(bundle, device("vendor-ipad-02", "iPad Air MSPT"));

        // Tier 3: Observation, DiagnosticReport, QuestionnaireResponse
        addEntry(bundle, lclaObservation("assess-2001", "mod-lcla-001", "abc-1001"));
        addEntry(bundle, lclaObservation("assess-2002", "mod-lcla-002", "def-1002"));
        addEntry(bundle, observation("obs-9hpt-assess-2001-mod-001", "abc-1001",
                "assess-2001", "83141-2", "9-Hole Pegboard Dexterity Test"));
        addEntry(bundle, observation("obs-sdmt-assess-2001-mod-001", "abc-1001",
                "assess-2001", "72172-0", "Symbol Digit Modalities Test"));
        addEntry(bundle, observation("obs-t25fw-assess-2002-mod-001", "def-1002",
                "assess-2002", "72098-7", "Timed 25-Foot Walk"));

        addEntry(bundle, diagnosticReport("diag-mri-abc-1001-2026-01", "abc-1001"));
        addEntry(bundle, diagnosticReport("diag-mri-def-1002-2026-01", "def-1002"));

        addEntry(bundle, questionnaireResponse("qr-nq-assess-2001-mod-nq-001",
                "abc-1001", "assess-2001"));
        addEntry(bundle, questionnaireResponse("qr-mh-assess-2001-mod-mh-001",
                "abc-1001", "assess-2001"));

        return bundle;
    }

    /**
     * Minimal valid bundle with a single patient.
     */
    public static Bundle minimalBundle() {
        Bundle bundle = new Bundle();
        bundle.setType(BundleType.COLLECTION);
        addEntry(bundle, patientAbc());
        return bundle;
    }

    /**
     * Empty bundle (no entries) — should trigger DIGIPHENOMS-001.
     */
    public static Bundle emptyBundle() {
        Bundle bundle = new Bundle();
        bundle.setType(BundleType.COLLECTION);
        return bundle;
    }

    /**
     * Bundle with only non-Patient resources — should trigger DIGIPHENOMS-002.
     */
    public static Bundle bundleWithoutPatient() {
        Bundle bundle = new Bundle();
        bundle.setType(BundleType.COLLECTION);
        addEntry(bundle, observation("obs-1", "abc-1001", "assess-2001",
                "79880-1", "LCLA"));
        return bundle;
    }

    private static void addEntry(Bundle bundle, Resource resource) {
        BundleEntryComponent entry = bundle.addEntry();
        entry.setResource(resource);
        entry.setFullUrl("urn:uuid:" + java.util.UUID.randomUUID());
    }

    // -----------------------------------------------------------------------
    // Mock response helpers
    // -----------------------------------------------------------------------

    /**
     * Build a mock transaction response bundle where all entries return 201 Created.
     */
    public static Bundle allCreatedResponse(int count) {
        Bundle response = new Bundle();
        response.setType(BundleType.TRANSACTIONRESPONSE);
        for (int i = 0; i < count; i++) {
            response.addEntry().getResponse().setStatus("201 Created");
        }
        return response;
    }

    /**
     * Build a mock transaction response with a mix of 201 Created and 200 OK.
     */
    public static Bundle mixedResponse(int created, int updated) {
        Bundle response = new Bundle();
        response.setType(BundleType.TRANSACTIONRESPONSE);
        for (int i = 0; i < created; i++) {
            response.addEntry().getResponse().setStatus("201 Created");
        }
        for (int i = 0; i < updated; i++) {
            response.addEntry().getResponse().setStatus("200 OK");
        }
        return response;
    }

    /**
     * Build a search result bundle containing the given resource.
     */
    public static Bundle searchResult(Resource... resources) {
        Bundle b = new Bundle();
        b.setType(BundleType.SEARCHSET);
        b.setTotal(resources.length);
        for (Resource r : resources) {
            b.addEntry().setResource(r);
        }
        return b;
    }

    /**
     * Empty search result bundle.
     */
    public static Bundle emptySearchResult() {
        Bundle b = new Bundle();
        b.setType(BundleType.SEARCHSET);
        b.setTotal(0);
        return b;
    }
}
